### ISSUE TITLE
Did something break?

### ISSUE THREAD

**Issue by edukaded** [openeth-dev/gsn#269]
Relayed this tx yesterday
https://etherscan.io/tx/0xe33d146224aad4aca2e76f7db2ebd64eff11e667a64ae7bc789cc00ff4e8d1db

I am not seeing where a fee was collected.  Am I missing something?  It seems my relay worked, it paid the gas but got nothing in return?

Thanks!

**Comment by shahafn** [comment]
The relay itself doesn't get the fee, the hub increases the owner's balance, and that can be withdrawn anytime. So you can just query `balanceOf(<relayOwner>)` and see that the owner received the charge.

**Comment by edukaded** [comment]
Ahh ok, that makes sense.  I see it now, thanks!
https://etherscan.io/address/0xd216153c06e857cd7f72665e0af1d7d82172f494#readContract
